--Comprobamos que el nombre sea correcto

SELECT ENTITY_NAME
FROM AGRIDS_V2.DBO.LCC_CIUDADES_TIPO_PROJECT_V9
WHERE ENTITY_NAME IN (
'ALBAIDADELALJARAFE',
'ASPE',
'BENIARBEIG',
'BENIARRES',
'BENIMELI',
'BETERA',
'CARRIONDELOSCESPEDES',
'CASTELLODELARIBERA',
'CONSTANTINA',
'GUADASSUAR',
'LOLLERIA',
'NAQUERA'
)
ORDER BY 1

select * from AGRIDS_V2.DBO.LCC_CIUDADES_TIPO_PROJECT_V9
where entity_name like '%olleria%'

--Sino hacemos el update en las siguientes tablas
UPDATE AGRIDS_V2.DBO.LCC_CIUDADES_TIPO_PROJECT_V9
SET ENTITY_NAME='LOLLERIA'
WHERE ENTITY_NAME='OLLERIA'

UPDATE AGRIDS.DBO.lcc_dashboard_info_scopes_NEW
SET ENTITIES_BBDD='LOLLERIA'
WHERE ENTITIES_BBDD='OLLERIA'

